kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Chart.Name }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Chart.Name }}-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Release.Name }}
          image: {{ .Values.image.url }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: '{{ .value }}'
            {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      imagePullSecrets:
        - name: {{ .Chart.Name }}-{{ .Release.Name }}-credentials